# .air.toml file
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./cmd/tmp/main.exe ./cmd"
bin = ""
full_bin = "./cmd/tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
include_dirs = []

[log]
time = false

[misc]
clean_on_exit = true

[watcher]
paths = ["./cmd", "./internals", "./configs", "/app","./packages"]