version: "3"
services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile # Specify the dev Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    environment:
      - ENV=development # Set environment variable for development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal-net

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=master
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-net
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  internal-net:
    driver: bridge
